server {
    listen 127.0.0.1:8080;
    server_name localhost;

    location / {
        root ./www/cgi-bash;
        index index.html;
        allowed_methods GET;
    }

    location /cgi-bin/ {
        root ./www/cgi-bash/cgi-bin;
        cgi_extension .sh;
        cgi_path /bin/bash;
        allowed_methods GET POST;
    }
}
