server {
    listen 127.0.0.1:8080;
    server_name localhost;

    location / {
        root ./www/cookies;
        index index.html;
        allowed_methods GET;
    }

    location /cgi-bin/ {
        root ./www/cookies/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        allowed_methods GET POST;
    }
}
