server {
    listen 127.0.0.1:8080;
    server_name localhost;

    client_max_body_size 2m;

    location / {
        root ./www/full;
        index index.html;
        allowed_methods GET;
    }

    location /cgi-bin/ {
        root ./www/full/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        allowed_methods GET POST DELETE;
    }

    location /data/posts/ {
        root ./www/full;
        autoindex on;
        allowed_methods GET DELETE;
    }
}
