server {
	listen 127.0.0.1:8080;
	server_name localhost;

	location / {
		root ./www/full;
		index index.html;
		allowed_methods GET;
	}

	location /files/ {
		root ./www/full/files;
		allowed_methods GET POST DELETE;
	}

	location /cgi-python/ {
		root ./www/full/cgi-python;
		cgi_extension .py;
		cgi_path /usr/bin/python3;
		allowed_methods GET POST;
	}

	location /cgi-bash/ {
		root ./www/full/cgi-bash;
		cgi_extension .sh;
		cgi_path /bin/bash;
		allowed_methods GET POST;
	}
}
