server {
    listen 127.0.0.1:8080;
    server_name alpha.localhost;

    location / {
        root ./www/multi-server/alpha;
        index index.html;
        allowed_methods GET;
        autoindex off;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name beta.localhost;

    location / {
        root ./www/multi-server/beta;
        index index.html;
        allowed_methods GET;
        autoindex on;
    }
}
