server {
    listen 127.0.0.1:8080;
    server_name localhost;

    location /old/ {
        return 301 /new/;
    }

    location /new/ {
        root ./www/html;
        index index.html;
        allowed_methods GET;
    }
}
