server {
    listen 127.0.0.1:8080;
    server_name localhost;
    client_max_body_size 200m;

    location / {
        root ./www/default;
        index index.html;
        allowed_methods GET;
    }

    location /post_body {
        root ./www/default;
        index tester_post_body.txt;
        allowed_methods POST;
        client_max_body_size 100;
    }

    location /directory {
        root ./YoupiBanane;
        return 301 /directory/;
    }

    location /directory/ {
        root ./YoupiBanane;
        index youpi.bad_extension;
        allowed_methods GET POST;
        client_max_body_size 200m;
        cgi_extension .bla;
        cgi_path ./cgi_tester;
    }
}
